version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: docker build -t onefastsnail/development:$CIRCLE_BRANCH .

     - run: docker push onefastsnail/development:$CIRCLE_BRANCH