version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: 
        name: 'Login to Dockhub'
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: 
        name: 'Build image and run basic tests'
        command: |
          THETAG=$(git describe --tags --abbrev=0)
          docker build -t onefastsnail/development:$THETAG -t onefastsnail/development:latest .
          docker run -it --rm onefastsnail/development:$THETAG node -v
          docker run -it --rm onefastsnail/development:$THETAG yarn -v
          docker run -it --rm onefastsnail/development:$THETAG php -v
          docker run -it --rm onefastsnail/development:$THETAG composer --version
          docker run -it --rm onefastsnail/development:$THETAG wp --allow-root --version
          docker push onefastsnail/development:latest
          docker push onefastsnail/development:$THETAG