version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: THETAG=$(git describe --tags --abbrev=0)

     - run: docker build -t onefastsnail/development:$THETAG -t onefastsnail/development:latest .

     # some very basic test commands of the packages we should installed
     - run: docker run -it --rm onefastsnail/development:$THETAG node -v
     - run: docker run -it --rm onefastsnail/development:$THETAG yarn -v
     - run: docker run -it --rm onefastsnail/development:$THETAG php -v
     - run: docker run -it --rm onefastsnail/development:$THETAG composer --version
     - run: docker run -it --rm onefastsnail/development:$THETAG wp --allow-root --version

     - run: docker push onefastsnail/development:latest
     - run: docker push onefastsnail/development:$THETAG